#!/bin/sh

# shellcheck disable=SC2068

docker compose exec node sh -c "if [ -d /app/keys ]; then echo 'Removendo diretório existente no container...'; rm -rf /app/keys; fi"

docker compose exec node sh -c "mkdir -p /app/keys && chmod 700 /app/keys"

docker compose exec node sh -c "openssl genrsa -out /app/keys/private.pem 2048"
docker compose exec node sh -c "openssl rsa -in /app/keys/private.pem -pubout -out /app/keys/public.pem"

echo "Chaves RSA geradas com sucesso no container em './keys'."